# Generated by Django 6.0.3 on 2026-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_category_image_fooditem_created_at_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'Manager')], default='customer', max_length=10),
        ),
    ]
